import utilidades as util

util.generarMenu()

"""Proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJAgu52yi3dm7TgFi7D7ygTcx_HR_o_l

# **Lectura y limpieza de datos**

### 1. Importamos las librerías que vamos a necesitar 


import pandas as pd
import time
import datetime
import matplotlib.pyplot as plt
import seaborn as sns

"""
